### ISSUE TITLE
Properties question for a single object

### ISSUE THREAD

**Issue by variolam** [Firefloat/lifelong-learning-ptr#2]
New `.json` file for questions about the properties of a single object (3-5 different formulations):
- [x] Questions about the color
- [x] Questions about parts, e.g. how many legs, doors etc.

**Comment by angelonti** [comment]
Implemented a total of 6 questions for single objects.

One issue was with questions with empty arguments (incomplete). To address this issue I created a NOT_NULL constraint so only complete questions can be created.
