### ISSUE TITLE
Adjust the code to generate only a specific type of quesion

### ISSUE THREAD

**Issue by variolam** [Firefloat/lifelong-learning-ptr#3]
It should be possible to create a single type of question for a scene, e.g. only what-questions or only analogies. Either adjust the code or create a small script that filters the output of the code.

**Comment by angelonti** [comment]
The feature was implemented as follows:

* Added a new parameter "template_types"
* The template types to be used are passed as a comma-separated list of template type names.
* If '*' is passed that means to use all, this is also the default value.

example:
--template_types what_question,zero_hop
